# Generated by Django 4.2.4 on 2023-09-07 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_education_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='language',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranks', to='accounts.profile'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='accounts.profile'),
        ),
    ]
