# Generated by Django 4.2.4 on 2023-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_award_profile_alter_certification_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
