# Generated by Django 4.2.4 on 2023-09-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_rank_delete_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='course',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
