# Generated by Django 4.2.4 on 2023-09-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersupportissue',
            name='body',
            field=models.TextField(),
        ),
    ]
