# Generated by Django 4.2.4 on 2023-09-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_usersupportissue_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersupportissue',
            name='from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
